#!/bin/bash

compile=$(javac -d classes/ -cp src/ src/tasks/TaskThree.java)
if [[ $compile -eq 0 ]]; then
   java -cp classes/ tasks.TaskThree location_room_mapping.csv location_archival_2014_2_1-0.csv location_archival_2014_2_1-1.csv location_archival_2014_2_1-2.csv location_archival_2014_2_1-3.csv location_archival_2014_2_1-4.csv location_archival_2014_2_1-5.csv
  #java -cp classes/ tasks.TaskOne location_room_mapping.csv location_archival_2014_2_1-0.csv location_archival_2014_2_1-1.csv
#java -cp classes/ tasks.TaskOne test_set.csv
fi